### ISSUE TITLE
Paris Prototyping Meta Issue

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/paris_1970#1]
- [x] Create a photo view which you can access with `/photos/1/` and make it look like the wire frame #2 
- [x] Homepage displays Map Square headings with a list of links underneath them #3 
- [x] Add front and back image URLs and other metadata to the Photograph model #4

**Comment by ryaanahmed** [comment]
All done!
